# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
