# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_img',
            field=models.ImageField(default=datetime.datetime(2016, 3, 7, 16, 1, 58, 973164, tzinfo=utc), upload_to='movie_img'),
            preserve_default=False,
        ),
    ]
