# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer_img',
            new_name='trailerimg',
        ),
    ]
